package dev.worldmind.region;

public enum RegionalOutcome {
    STASIS,
    VEGETATION_SPREAD,
    VEGETATION_THINNING,
    RECLAMATION,
    FARM_SUCCESSION,
    ROUTE_FORMATION,
    VILLAGE_GROWTH,
    VILLAGE_DECLINE,
    FORTIFICATION,
    PLACE_TRANSFORMATION,
    HISTORIC_REOCCUPATION,
    ANOMALY_MANIFESTATION
}
