package dev.worldmind.region;

public enum SpatialProcess {
    NONE,
    FOREST_FRONTIER,
    VEGETATION_PATCH,
    RECLAMATION_PATCH,
    FARM_SUCCESSION_PATCH,
    ROUTE_CORRIDOR,
    SETTLEMENT_GROWTH_EDGE,
    SETTLEMENT_DECLINE_PATCH,
    FORTIFICATION_EDGE,
    PLACE_DOMAIN,
    HISTORIC_REOCCUPATION_SITE,
    ANOMALY_SITE
}
